version: "3.8"

services:
  app:
    container_name: react-training
    image: react-training
    build:
      context: .
      target: development
    volumes:
      - ./src:/react-training/src
    ports:
      - 3000:3000